exec-once = waybar
exec-once = mako
exec-once = swayosd-server
exec-once = hypridle -c ~/.config/hypr/hypridle.conf
exec-once = ~/.config/scripts/set-wallpaper.sh --restore
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=Hyprland
