$gruvbox_bg0 = rgb(282828)
$gruvbox_bg0_soft = rgb(32302f)
$gruvbox_bg1 = rgb(3c3836)
$gruvbox_bg2 = rgb(504945)
$gruvbox_bg3 = rgb(665c54)
$gruvbox_fg0 = rgb(fbf1c7)
$gruvbox_fg1 = rgb(ebdbb2)
$gruvbox_fg2 = rgb(d5c4a1)
$gruvbox_fg3 = rgb(bdae93)
$gruvbox_red = rgb(fb4934)
$gruvbox_green = rgb(b8bb26)
$gruvbox_yellow = rgb(fabd2f)
$gruvbox_blue = rgb(83a598)
$gruvbox_purple = rgb(d3869b)
$gruvbox_aqua = rgb(8ec07c)
$gruvbox_orange = rgb(fe8019)
