general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = bash -lc 'loginctl lock-session; pidof hyprlock >/dev/null || hyprlock'
    after_sleep_cmd = bash -lc 'hyprctl dispatch dpms on; brightnessctl -r || true'
    ignore_dbus_inhibit = false
    ignore_systemd_inhibit = false
    ignore_wayland_inhibit = false
}

listener {
    timeout = 60
    on-timeout = bash ~/.config/scripts/idle-power.sh dim battery
    on-resume = bash ~/.config/scripts/idle-power.sh resume battery
}

listener {
    timeout = 180
    on-timeout = bash ~/.config/scripts/idle-power.sh off battery
    on-resume = bash ~/.config/scripts/idle-power.sh resume battery
}

listener {
    timeout = 300
    on-timeout = bash ~/.config/scripts/idle-power.sh suspend battery
}

listener {
    timeout = 300
    on-timeout = bash ~/.config/scripts/idle-power.sh dim ac
    on-resume = bash ~/.config/scripts/idle-power.sh resume ac
}

listener {
    timeout = 600
    on-timeout = bash ~/.config/scripts/idle-power.sh off ac
    on-resume = bash ~/.config/scripts/idle-power.sh resume ac
}

listener {
    timeout = 1200
    on-timeout = bash ~/.config/scripts/idle-power.sh suspend ac
}
