# Main Hyprland entry point. Keep this file small and delegate to focused config files.

source = ~/.config/hypr/conf.d/monitors.conf
source = ~/.config/hypr/conf.d/apps.conf
source = ~/.config/hypr/conf.d/autostart.conf
source = ~/.config/hypr/conf.d/environment.conf
source = ~/.config/hypr/conf.d/permissions.conf
source = ~/.config/hypr/conf.d/look-and-feel.conf
source = ~/.config/hypr/conf.d/input.conf
source = ~/.config/hypr/conf.d/keybinds.conf
source = ~/.config/hypr/conf.d/windows-and-workspaces.conf
